# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"$\n\x07\x41rticle\x12\n\n\x02Id\x18\x01 \x01(\t\x12\r\n\x05Price\x18\x02 \x01(\t\"?\n\x0f\x41rticleResponse\x12\n\n\x02Id\x18\x01 \x01(\t\x12\r\n\x05Price\x18\x02 \x01(\t\x12\x11\n\tavailable\x18\x03 \x01(\x08\"5\n\x0f\x41rticlesRequest\x12\"\n\x08\x41rticles\x18\x01 \x03(\x0b\x32\x10.product.Article\"B\n\x14\x41vailabilityResponse\x12*\n\x08\x41rticles\x18\x01 \x03(\x0b\x32\x18.product.ArticleResponse2^\n\x0eProductService\x12L\n\x11\x43heckAvailability\x12\x18.product.ArticlesRequest\x1a\x1d.product.AvailabilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARTICLE']._serialized_start=26
  _globals['_ARTICLE']._serialized_end=62
  _globals['_ARTICLERESPONSE']._serialized_start=64
  _globals['_ARTICLERESPONSE']._serialized_end=127
  _globals['_ARTICLESREQUEST']._serialized_start=129
  _globals['_ARTICLESREQUEST']._serialized_end=182
  _globals['_AVAILABILITYRESPONSE']._serialized_start=184
  _globals['_AVAILABILITYRESPONSE']._serialized_end=250
  _globals['_PRODUCTSERVICE']._serialized_start=252
  _globals['_PRODUCTSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
